### ISSUE TITLE
Unhandled Exception: System.AggregateException: One or more errors occurred.

### ISSUE THREAD

**Issue by kashcode** [kenkendk/ceenhttpd#10]
When I compile in Debug mode and run from bin\Debug folder everything started fine.
Error appear when I press key for stopping server.
What I need to do for handle this error? 

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
   at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)
   at Ceen.Httpd.HttpServer.RunnerControl.Stop(String logtaskid)
   at Ceen.Httpd.HttpServer.RunnerControl.<.ctor>b__27_0()
   at System.Threading.CancellationToken.ActionToActionObjShunt(Object obj)
   at System.Threading.CancellationCallbackInfo.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationCallbackInfo.ExecuteCallback()
   at System.Threading.CancellationTokenSource.CancellationCallbackCoreWork(CancellationCallbackCoreWorkArguments args)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.Cancel()
   at ConsoleApp1.Program.Main(String[] args) in D:\dotnet\ConsoleApp2\ConsoleApp1\Program.cs:line 43
```

**Comment by kashcode** [comment]
InnerException:
```
An attempt was made to transition a task to a final state when it had already completed.
```

**Comment by kenkendk** [comment]
I think I fixed this: https://github.com/kenkendk/ceenhttpd/commit/bf172f14ee6309a7298d6ebcb2c72b3d30c25ed9

If you try the latest build, it should be fixed.

**Comment by kashcode** [comment]
Update nuget from 0.9.6 to 0.9.7 fixes error

**Comment by zimorodokan** [comment]
I downloaded the last zip version from https://github.com/kerams/memrise-scraper/releases/tag/v1.0.1

D:\temp\MemriseScraper>MemriseScraper.exe 1096816
..........
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Unexpected column kind
   at Program.mapping@1(String tupledArg0, JsonValue tupledArg1)
   at Program.unifyColumnsAndAttributes(IJsonDocument thing)
   at Program.main@127-1.Invoke(HtmlNode w)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
   at Program.main@120.Invoke(String level)
   at Microsoft.FSharp.Collections.ArrayModule.Parallel.Map@1324-3.Invoke(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at Microsoft.FSharp.Collections.ArrayModule.Parallel.Map[T,TResult](FSharpFunc`2 mapping, T[] array)
   at Program.main(String[] argv)

**Comment by kenkendk** [comment]
Wrong repo, @zimorodokan
